import { ConnectedAccount, Item, Workspace, DailyBriefing } from '@/types';

export const DEMO_ACCOUNTS: ConnectedAccount[] = [
  {
    id: 'acc-1',
    user_id: 'demo-user-1',
    provider: 'google',
    email: 'alex.student@gmail.com',
    label: 'Personal Google',
    color: '#10b981', // emerald
    status: 'connected',
    last_synced_at: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    sync_enabled_types: ['email', 'event', 'deadline', 'task', 'file'],
    created_at: new Date(Date.now() - 30 * 86400 * 1000).toISOString(),
  },
  {
    id: 'acc-2',
    user_id: 'demo-user-1',
    provider: 'microsoft',
    email: 'alex.chen@cornell.edu',
    label: 'Cornell Outlook',
    color: '#3b82f6', // blue
    status: 'connected',
    last_synced_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    sync_enabled_types: ['email', 'event', 'deadline', 'task'],
    created_at: new Date(Date.now() - 25 * 86400 * 1000).toISOString(),
  },
  {
    id: 'acc-3',
    user_id: 'demo-user-1',
    provider: 'google',
    email: 'alex@hypergrowth.tech',
    label: 'Work Workspace',
    color: '#8b5cf6', // purple
    status: 'connected',
    last_synced_at: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    sync_enabled_types: ['email', 'event', 'deadline', 'file'],
    created_at: new Date(Date.now() - 18 * 86400 * 1000).toISOString(),
  },
  {
    id: 'acc-4',
    user_id: 'demo-user-1',
    provider: 'canvas',
    email: 'achen42@canvas.cornell.edu',
    label: 'Cornell Canvas LMS',
    color: '#f59e0b', // amber
    status: 'connected',
    last_synced_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    sync_enabled_types: ['deadline', 'task', 'file'],
    created_at: new Date(Date.now() - 20 * 86400 * 1000).toISOString(),
  },
  {
    id: 'acc-5',
    user_id: 'demo-user-1',
    provider: 'github',
    email: 'alexchen-dev',
    label: 'GitHub Octocat',
    color: '#64748b', // slate
    status: 'needs_reconnect',
    error_message: 'Access token expired 12h ago. Reconnect to resume issues sync.',
    last_synced_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    sync_enabled_types: ['task', 'deadline'],
    created_at: new Date(Date.now() - 40 * 86400 * 1000).toISOString(),
  },
];

const now = new Date();
const addHours = (h: number) => new Date(now.getTime() + h * 3600 * 1000).toISOString();
const subHours = (h: number) => new Date(now.getTime() - h * 3600 * 1000).toISOString();
const addDays = (d: number) => new Date(now.getTime() + d * 86400 * 1000).toISOString();

export const DEMO_ITEMS: Item[] = [
  // --- OVERDUE DEADLINE ---
  {
    id: 'item-1',
    user_id: 'demo-user-1',
    account_id: 'acc-4',
    type: 'deadline',
    title: 'CS 4410 Operating Systems Lab 3: Virtual Memory Page Replacement',
    description: 'Implement LRU and Second-Chance paging algorithms in C. Submit via CMSX.',
    due_at: subHours(2),
    priority_score: 95,
    is_done: false,
    source_id: 'canvas-assn-4410-03',
    url: 'https://canvas.cornell.edu/courses/31821/assignments/10928',
    metadata: {
      course_name: 'CS 4410 - Operating Systems',
      urgent_keywords: ['submit', 'lab', 'virtual memory'],
    },
    created_at: subHours(48),
    updated_at: now.toISOString(),
  },

  // --- DUE TODAY (URGENT) ---
  {
    id: 'item-2',
    user_id: 'demo-user-1',
    account_id: 'acc-4',
    type: 'deadline',
    title: 'INFO 4300 Information Architecture: Midterm Heuristic Evaluation',
    description: 'Upload peer review of redesign mockups with accessibility checklist.',
    due_at: addHours(3.5),
    priority_score: 88,
    is_done: false,
    source_id: 'canvas-assn-4300-midterm',
    url: 'https://canvas.cornell.edu/courses/29104/assignments/8817',
    metadata: {
      course_name: 'INFO 4300 - Info Arch',
      urgent_keywords: ['midterm', 'evaluation', 'deadline'],
    },
    created_at: subHours(72),
    updated_at: now.toISOString(),
  },

  // --- DUE TONIGHT ---
  {
    id: 'item-3',
    user_id: 'demo-user-1',
    account_id: 'acc-3',
    type: 'task',
    title: 'Push V2 Auth Migration RFC & Schema Pull Request',
    description: 'Finalize Postgres RLS policy audit for client tokens before staging freeze.',
    due_at: addHours(6),
    priority_score: 82,
    is_done: false,
    source_id: 'gh-pr-142',
    url: 'https://github.com/hypergrowth/platform/pull/142',
    metadata: {
      urgent_keywords: ['RFC', 'migration', 'urgent'],
    },
    created_at: subHours(10),
    updated_at: now.toISOString(),
  },

  // --- DUE THIS WEEK ---
  {
    id: 'item-4',
    user_id: 'demo-user-1',
    account_id: 'acc-4',
    type: 'deadline',
    title: 'MATH 2940 Linear Algebra Problem Set 7: SVD & Eigenvectors',
    description: 'Odd numbered problems 1-27 from Chapter 7 with LaTeX writeup.',
    due_at: addDays(2),
    priority_score: 72,
    is_done: false,
    source_id: 'canvas-math-ps7',
    url: 'https://canvas.cornell.edu/courses/30112/assignments/9912',
    metadata: {
      course_name: 'MATH 2940 - Linear Algebra',
    },
    created_at: subHours(24),
    updated_at: now.toISOString(),
  },
  {
    id: 'item-5',
    user_id: 'demo-user-1',
    account_id: 'acc-2',
    type: 'deadline',
    title: 'ECE Capstone Project Milestone 2: Hardware Prototype Demo',
    description: 'In-person check-in with Prof. Martinez in Phillips Hall 214.',
    due_at: addDays(4),
    priority_score: 65,
    is_done: false,
    source_id: 'outlook-capstone-m2',
    metadata: {
      course_name: 'ECE 4920 - Senior Design',
    },
    created_at: subHours(12),
    updated_at: now.toISOString(),
  },

  // --- CALENDAR EVENTS (TODAY) ---
  {
    id: 'item-6',
    user_id: 'demo-user-1',
    account_id: 'acc-2',
    type: 'event',
    title: 'CS 4410 Distributed Systems Lecture: Raft Consensus',
    description: 'Gates Hall G01 with Prof. Van Renesse',
    start_at: addHours(0.75),
    end_at: addHours(1.75),
    priority_score: 90,
    is_done: false,
    source_id: 'cal-event-cs4410',
    url: 'https://cornell.zoom.us/j/94829104',
    metadata: {
      location: 'Gates Hall G01 / Zoom',
      course_name: 'CS 4410',
    },
    created_at: subHours(100),
    updated_at: now.toISOString(),
  },
  {
    id: 'item-7',
    user_id: 'demo-user-1',
    account_id: 'acc-3',
    type: 'event',
    title: 'Platform Architecture Sync: Multi-Tenant Database Sharding',
    description: 'Weekly team sprint review on Google Meet.',
    start_at: addHours(2.5),
    end_at: addHours(3.25),
    priority_score: 85,
    is_done: false,
    source_id: 'cal-event-work-sharding',
    url: 'https://meet.google.com/xyz-abcd-efg',
    metadata: {
      location: 'Google Meet',
    },
    created_at: subHours(150),
    updated_at: now.toISOString(),
  },
  {
    id: 'item-8',
    user_id: 'demo-user-1',
    account_id: 'acc-2',
    type: 'event',
    title: 'Office Hours with TA: Virtual Memory Debugging',
    description: 'Rhodes Hall 4th floor lounge.',
    start_at: addHours(4.5),
    end_at: addHours(5.5),
    priority_score: 60,
    is_done: false,
    source_id: 'cal-event-ta-oh',
    metadata: {
      location: 'Rhodes 408',
    },
    created_at: subHours(40),
    updated_at: now.toISOString(),
  },

  // --- KEY EMAILS & ACTION ITEMS ---
  {
    id: 'item-9',
    user_id: 'demo-user-1',
    account_id: 'acc-2',
    type: 'email',
    title: 'Prof. Mark Van Renesse: Midterm Date Rescheduled to Next Thursday',
    description: 'Due to the campus conference, our midterm examination is shifted to Oct 8th in Bailey Hall.',
    priority_score: 92,
    is_done: false,
    source_id: 'email-corn-prof-exam',
    url: 'https://outlook.office.com/mail/id/194821',
    metadata: {
      sender: 'mvr@cs.cornell.edu',
      urgent_keywords: ['midterm', 'rescheduled', 'exam'],
    },
    created_at: subHours(1.5),
    updated_at: now.toISOString(),
  },
  {
    id: 'item-10',
    user_id: 'demo-user-1',
    account_id: 'acc-1',
    type: 'email',
    title: 'United Airlines: E-Ticket Confirmation for Flight UA 1429 (BOS -> SFO)',
    description: 'Flight departs Nov 24, 2026. Terminal B, Gate 22. Confirmation #K9P84L.',
    priority_score: 65,
    is_done: false,
    source_id: 'email-united-k9p84l',
    url: 'https://mail.google.com/mail/u/0/#inbox/18f9210bca',
    metadata: {
      sender: 'confirmations@united.com',
      travel_data: {
        booking_ref: 'K9P84L',
        flight_or_hotel: 'Flight UA 1429 (BOS -> SFO)',
        date_range: 'Nov 24, 2026 - 08:30 AM',
      },
    },
    created_at: subHours(14),
    updated_at: now.toISOString(),
  },
  {
    id: 'item-11',
    user_id: 'demo-user-1',
    account_id: 'acc-3',
    type: 'email',
    title: 'AWS Billing Alert: Monthly Threshold Exceeded ($142.80)',
    description: 'Your production RDS replica instance usage reached 85% of budget threshold.',
    priority_score: 75,
    is_done: false,
    source_id: 'email-aws-alert-0929',
    url: 'https://mail.google.com/mail/u/1/#inbox/18f9188a10',
    metadata: {
      sender: 'no-reply-aws@amazon.com',
      bill_data: {
        amount: '$142.80',
        currency: 'USD',
        due_date: 'Oct 03, 2026',
        merchant: 'Amazon Web Services',
      },
    },
    created_at: subHours(5),
    updated_at: now.toISOString(),
  },

  // --- PINNED & IMPORTANT FILES ---
  {
    id: 'item-12',
    user_id: 'demo-user-1',
    account_id: 'acc-1',
    type: 'file',
    title: 'Distributed_Systems_CheatSheet_Finals.pdf',
    description: 'Summaries of Paxos, Raft, Two-Phase Commit, and Vector Clocks.',
    priority_score: 70,
    is_done: false,
    source_id: 'drive-file-cscheatsheet',
    url: 'https://drive.google.com/file/d/108391083921/view',
    metadata: {
      pinned: true,
      file_type: 'PDF',
      file_size_formatted: '4.2 MB',
      course_name: 'CS 4410',
    },
    created_at: subHours(120),
    updated_at: now.toISOString(),
  },
  {
    id: 'item-13',
    user_id: 'demo-user-1',
    account_id: 'acc-2',
    type: 'file',
    title: 'INFO_4300_Design_Tokens_Figma_Handoff.fig',
    description: 'Final component system specifications and spacing matrix.',
    priority_score: 68,
    is_done: false,
    source_id: 'onedrive-file-figma',
    url: 'https://cornell-my.sharepoint.com/personal/achen42/info4300.fig',
    metadata: {
      pinned: true,
      file_type: 'FIG',
      file_size_formatted: '18.7 MB',
      course_name: 'INFO 4300',
    },
    created_at: subHours(80),
    updated_at: now.toISOString(),
  },
  {
    id: 'item-14',
    user_id: 'demo-user-1',
    account_id: 'acc-3',
    type: 'file',
    title: 'UnifyHub_Architecture_V2_Draft.docx',
    description: 'Technical specification for Edge Function synchronization pipelines.',
    priority_score: 80,
    is_done: false,
    source_id: 'drive-file-unifyhub-arch',
    url: 'https://drive.google.com/file/d/9871239812/view',
    metadata: {
      pinned: true,
      file_type: 'DOCX',
      file_size_formatted: '1.1 MB',
    },
    created_at: subHours(16),
    updated_at: now.toISOString(),
  },
];

export const DEMO_WORKSPACES: Workspace[] = [
  {
    id: 'ws-all',
    user_id: 'demo-user-1',
    name: 'All Combined',
    slug: 'all',
    icon: 'Layers',
    account_ids: ['acc-1', 'acc-2', 'acc-3', 'acc-4', 'acc-5'],
    included_types: ['email', 'event', 'deadline', 'task', 'file'],
    is_default: true,
  },
  {
    id: 'ws-college',
    user_id: 'demo-user-1',
    name: 'College & Courses',
    slug: 'college',
    icon: 'GraduationCap',
    account_ids: ['acc-2', 'acc-4'],
    included_types: ['deadline', 'event', 'file', 'task'],
    is_default: false,
  },
  {
    id: 'ws-work',
    user_id: 'demo-user-1',
    name: 'Tech Work',
    slug: 'work',
    icon: 'Briefcase',
    account_ids: ['acc-3', 'acc-5'],
    included_types: ['email', 'event', 'deadline', 'task', 'file'],
    is_default: false,
  },
  {
    id: 'ws-personal',
    user_id: 'demo-user-1',
    name: 'Personal Life',
    slug: 'personal',
    icon: 'User',
    account_ids: ['acc-1'],
    included_types: ['email', 'event', 'deadline', 'file'],
    is_default: false,
  },
];

export const DEMO_BRIEFING: DailyBriefing = {
  id: 'brief-01',
  date: new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric' }),
  headline: '3 major deadlines today, 1 overdue lab, and 2 key lectures scheduled.',
  summary:
    'You have OS Lab 3 2 hours overdue and Info Arch evaluation due in 3.5 hours. CS 4410 lecture starts in 45 minutes. A 90-minute free window opens up between 11:30 AM and 1:00 PM for focused coursework.',
  urgent_count: 2,
  meetings_count: 3,
  free_slots_summary: '11:30 AM - 1:00 PM (90m), 3:15 PM - 4:30 PM (75m)',
  generated_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
};
